spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Options: none, create, create-drop, update, validate
    show-sql: true # Logs SQL queries to the console (optional)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always # Initializes the schema and data on startup (optional)